//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class ItemHandler : MonoBehaviour {

	// What to do when this item gets used.
	public abstract void Use();

	// Whether this item should disappear on use.
	public abstract bool Consumes();

}
