//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class ItemPlaySound : ItemHandler {

	public AudioClip sound2play;

	public override void Use () {
		AudioSource.PlayClipAtPoint(sound2play, Camera.main.transform.position);
	}

	public override bool Consumes() {
		return false;
	}

}
